### ISSUE TITLE
Step 3 is missing sudo

### ISSUE THREAD

**Issue by rmschaller** [sdr-enthusiasts/gitbook-adsb-guide#104]
Step 3 command should be issued as sudo.

**Comment by dziban303** [comment]
Not sure what step you're talking about. I don't think anything is numbered. But you're free to submit a pull request to fix it.

**Comment by mikenye** [comment]
@rmschaller can you provide more information please? Which page/section?

**Comment by tedder** [comment]
My guess is [this depmod command](https://sdr-enthusiasts.gitbook.io/ads-b/setting-up-rtl-sdrs/blacklist-kernel-modules#3.-rebuild-module-dependency-database)?

**Comment by kx1t** [comment]
fixed in this commit: https://github.com/sdr-enthusiasts/gitbook-adsb-guide/commit/d860c9bfbafd9696b6d6cfb2c48ddc6839748abc
