### ISSUE TITLE
autogain troubleshooting instructions don't seem to be accurate

### ISSUE THREAD

**Issue by joelishness** [sdr-enthusiasts/gitbook-adsb-guide#124]
Excerpt from deploy-ultrafeeder-container.md:
> To do this, please do the following. You may have to try different values instead of the value of 34 suggested here:
> 
>     Set the READSB_AUTOGAIN_INITIAL_GAIN variable in the ultrafeeder section of your docker-compose file:
> 
>     environment:
>       - READSB_AUTOGAIN_INITIAL_GAIN=34

This does not seem to have any affect, triggering autogain does not respect this setting.
I tried READSB_AUTOGAIN_INITIAL_GAIN=20, but it did not start at 20 as expected:
![image](https://github.com/sdr-enthusiasts/gitbook-adsb-guide/assets/5108006/7c4aab48-fdf6-40c9-8dea-13439eaa41e9)

Additionally, searching the ultrafeeder repo yields no results for "READSB_AUTOGAIN_INITIAL_GAIN" or "INITIAL_GAIN".

Does this environment variable really exist?

**Comment by joelishness** [comment]
Oh, I think it is likely because the container needs to be updated with the new variable before issuing the command.

So this would be out of order:
```
cd /opt/adsb
docker exec -it ultrafeeder autogain reset
docker compose up -d
```

Should be:
```
cd /opt/adsb
docker compose up -d
docker exec -it ultrafeeder autogain reset
```

But actually the reset command isn't correct anyway, should be:
```
cd /opt/adsb
docker compose up -d
docker exec -it ultrafeeder /usr/local/bin/autogain1090 reset
```
Per Pull request #122

**Comment by jimmy-devine** [comment]
+1, I was trying to set this too and it had no impact with `READSB_AUTOGAIN_INITIAL_GAIN` . Did you dig in to this at all? I suspect that wherever the initial gain is being set (outside of autogain) that it's not considering the variable. I'll post back if I find where it's happening.

**Comment by kx1t** [comment]
I'm going to close this issue:
- we merged a documentation update to clarify/correct how autogain can be reset https://github.com/sdr-enthusiasts/gitbook-adsb-guide/pull/122
- we recently fixed an issue that prevented autogain to be reset until the next restart of the container https://github.com/sdr-enthusiasts/docker-tar1090/commit/867d70a4db414648a5fa5e945ac2dea2d339b5b7

If the issues persist, feel free to reopen this bug
