### ISSUE TITLE
Need example UAT viewadsb output

### ISSUE THREAD

**Issue by mikenye** [sdr-enthusiasts/gitbook-adsb-guide#47]
Could someone receiving UAT please post the output of `viewadsb` showing UAT aircraft? The document lacks an example.

https://github.com/sdr-enthusiasts/gitbook-adsb-guide/blob/main/foundations/deploy-dump978-usa-only.md#viewing-live-data

Thanks.

**Comment by kx1t** [comment]
Done -- created `viewadsb` in the docker-dump978 container, and added this to the description.
References:
https://github.com/sdr-enthusiasts/gitbook-adsb-guide/commit/4371c64c55be2ea641456baf437aca3bad0a252e
https://github.com/sdr-enthusiasts/docker-dump978/commit/ad59eb973defd069d28f598686415909f9c09959
