### ISSUE TITLE
InfluxDB mentioned on Overview but section missing

### ISSUE THREAD

**Issue by luciodaou** [sdr-enthusiasts/gitbook-adsb-guide#59]
As described on title, Overview section mentions the use of InfluxDB:
https://github.com/sdr-enthusiasts/gitbook-adsb-guide/blob/34e4d455fd5011444c049127277aab1bede27510/intro/overview.md?plain=1#L7

But there's no section with these instructions.

**Comment by mikenye** [comment]
Resolved via #71. Thanks @wandering-andy.
