### ISSUE TITLE
Feature Request: BIAS-T support to enable use of low noise amplifier

### ISSUE THREAD

**Issue by TheNopePlant** [sdr-enthusiasts/gitbook-adsb-guide#60]
Hi All,

Keen to try your guide out as this show allow me to feed to more sites with relative ease.

Is it possible to add BIAS-T voltage support somewhere to enable the passthrough of 5V power through to a low noise amplifier?

**Comment by mikenye** [comment]
You can add the environment variable `READSB_ENABLE_BIASTEE=true` to your `readsb` container. This should enable Bias-T support provided your hardware supports it.
