### ISSUE TITLE
RPI but unknown server OS

### ISSUE THREAD

**Issue by hodgkiss** [sdr-enthusiasts/gitbook-adsb-guide#91]
Issue on 
docker run --rm -it --device /dev/bus/usb --entrypoint rtl_eeprom ghcr.io/sdr-enthusiasts/docker-readsb-protobuf -s 1090

from page: https://sdr-enthusiasts.gitbook.io/ads-b/setting-up-rtl-sdrs/re-serialise-sdrs

result issue: on RPI 4gb ram
docker: unknown server OS: .

**Comment by tedder** [comment]
What does it say if you change `-s 1090` to `-h`?

What does `uname -a` return?

Have you been running other docker commands or is this the first?

**Comment by hodgkiss** [comment]
The first usage - was using this guide only.
Did repeat usage of the command, same error.

**Comment by hodgkiss** [comment]
What does it say if you change -s 1090 to -h?
* same error

What does uname -a return?
Linux radardocker###
 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux

**Comment by hodgkiss** [comment]
Going to format the SD card and try again.

**Comment by tedder** [comment]
Does this run successfully?
```
sudo docker run --rm hello-world
```

If you installed it using the guidebook and the docker install script, you need to log out and back in.

If you did the install yourself (`apt install docker`) you missed setting ownership and adding `pi` to a group.

**Comment by hodgkiss** [comment]
Cant recreate the issue since the format and re-image of SD closing.

**Comment by mikenye** [comment]
@hodgkiss no problems, thanks for the update.
